In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

1 miles is 1.6 km 
1 gallon is  3.7 km

In [2]:
import warnings 
warnings.filterwarnings("ignore")

In [3]:
df = sns.load_dataset("mpg")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [4]:
df = df.drop("name", axis=1)
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa
394,44.0,4,97.0,52.0,2130,24.6,82,europe
395,32.0,4,135.0,84.0,2295,11.6,82,usa
396,28.0,4,120.0,79.0,2625,18.6,82,usa
397,31.0,4,119.0,82.0,2720,19.4,82,usa

In [5]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin              str
dtype: object

In [6]:
df.origin.unique()

<StringArray>
['usa', 'japan', 'europe']
Length: 3, dtype: str

In [7]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [8]:
df[df["horsepower"].isnull()]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
32,25.0,4,98.0,NaN,2046,19.0,71,usa
126,21.0,6,200.0,NaN,2875,17.0,74,usa
330,40.9,4,85.0,NaN,1835,17.3,80,europe
336,23.6,4,140.0,NaN,2905,14.3,80,usa
354,34.5,4,100.0,NaN,2320,15.8,81,europe
374,23.0,4,151.0,NaN,3035,20.5,82,usa

In [9]:
# since we have not done the outlier treatment lets replace the value with median
med = df.horsepower.median()
df["horsepower"] = df.horsepower.fillna(med)

In [10]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [11]:
df.origin.value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [12]:
new_df = pd.get_dummies(df["origin"])
new_df

     europe  japan    usa
0     False  False   True
1     False  False   True
2     False  False   True
3     False  False   True
4     False  False   True
..      ...    ...    ...
393   False  False   True
394    True  False  False
395   False  False   True
396   False  False   True
397   False  False   True

[398 rows x 3 columns]

In [13]:
# new_df = pd.get_dummies(df["origin"])
# df_new = new_df.astype("int64")

# df = pd.concat([df, df_new], axis=1)
# df = df.drop("origin", axis=1)

# df = df.drop("europe", axis=1)


df = pd.get_dummies(
    df,
    columns=["origin"],
    drop_first=True,
    dtype=int
)

In [14]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,18.0,8,307.0,130.0,3504,12.0,70,0,1
1,15.0,8,350.0,165.0,3693,11.5,70,0,1
2,18.0,8,318.0,150.0,3436,11.0,70,0,1
3,16.0,8,304.0,150.0,3433,12.0,70,0,1
4,17.0,8,302.0,140.0,3449,10.5,70,0,1
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,0,1
394,44.0,4,97.0,52.0,2130,24.6,82,0,0
395,32.0,4,135.0,84.0,2295,11.6,82,0,1
396,28.0,4,120.0,79.0,2625,18.6,82,0,1
397,31.0,4,119.0,82.0,2720,19.4,82,0,1

In [15]:
# we have done with encoding part

In [16]:
# find what x and y 
X = df.drop("mpg", axis=1)
y = df["mpg"]

In [17]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,8,307.0,130.0,3504,12.0,70,0,1
1,8,350.0,165.0,3693,11.5,70,0,1
2,8,318.0,150.0,3436,11.0,70,0,1
3,8,304.0,150.0,3433,12.0,70,0,1
4,8,302.0,140.0,3449,10.5,70,0,1
...,...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,0,1
394,4,97.0,52.0,2130,24.6,82,0,0
395,4,135.0,84.0,2295,11.6,82,0,1
396,4,120.0,79.0,2625,18.6,82,0,1
397,4,119.0,82.0,2720,19.4,82,0,1

In [18]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((298, 8), (100, 8), (298,), (100,))

In [20]:
# StandardScaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [21]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()

regression.fit(X_train_scaled, y_train)

LinearRegression()

In [22]:
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": regression.coef_
})

coef_df

        Feature  Coefficient
0     cylinders    -0.205487
1  displacement     1.644715
2    horsepower    -0.412485
3        weight    -5.694750
4  acceleration     0.206688
5    model_year     2.913184
6  origin_japan    -0.034942
7    origin_usa    -1.442799

In [23]:
# observation :
# coeff are very small 
# if one independent variable changes there is not much difference in rediction 
# this is something call smoother model

In [26]:
y_pred = regression.predict(X_test_scaled)
y_pred[:5]

array([32.57308613, 29.16515664, 21.04330147, 16.78717986, 12.40620928])

In [27]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("R2 Score :", r2_score(y_test, y_pred))
print("MAE      :", mean_absolute_error(y_test, y_pred))
print("MSE      :", mean_squared_error(y_test, y_pred))

R2 Score : 0.8430426014268103
MAE      : 2.3438469130057737
MSE      : 8.912592953199097

**Ridge Regression**

In [28]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=1.0)
# controls regularization strength.

# alpha = 0 → behaves like Linear Regression
# small alpha → weak regularization
# large alpha → strong regularization

In [29]:
# train 
ridge.fit(X_train_scaled, y_train)

Ridge()

In [30]:
ridge_coeff = pd.DataFrame({
    "Features" : X.columns,
    "Coeff" : ridge.coef_
}
)
ridge_coeff

       Features     Coeff
0     cylinders -0.172210
1  displacement  1.400206
2    horsepower -0.461030
3        weight -5.476664
4  acceleration  0.160778
5    model_year  2.883784
6  origin_japan -0.013368
7    origin_usa -1.406071

In [31]:
""" 
| Feature      | Linear |  Ridge |
| ------------ | -----: | -----: |
| cylinders    | -0.205 | -0.172 |
| displacement |  1.645 |  1.400 |
| horsepower   | -0.412 | -0.461 |
| weight       | -5.695 | -5.477 |
| acceleration |  0.207 |  0.161 |
| model_year   |  2.913 |  2.884 |
| origin_japan | -0.035 | -0.013 |
| origin_usa   | -1.443 | -1.406 |

"""

' \n| Feature      | Linear |  Ridge |\n| ------------ | -----: | -----: |\n| cylinders    | -0.205 | -0.172 |\n| displacement |  1.645 |  1.400 |\n| horsepower   | -0.412 | -0.461 |\n| weight       | -5.695 | -5.477 |\n| acceleration |  0.207 |  0.161 |\n| model_year   |  2.913 |  2.884 |\n| origin_japan | -0.035 | -0.013 |\n| origin_usa   | -1.443 | -1.406 |\n\n'

In [32]:
from sklearn.metrics import r2_score

print("Linear Regression R2 :",
      r2_score(y_test, regression.predict(X_test_scaled)))

print("Ridge R2 :",
      r2_score(y_test, ridge.predict(X_test_scaled)))

Linear Regression R2 : 0.8430426014268103
Ridge R2 : 0.842362621546747

In [33]:
for alpha in [0.01, 0.1, 1, 10, 100]:
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_train_scaled, y_train)

    print(
        f"Alpha={alpha}",
        "R2=",
        round(r2_score(y_test,
                       ridge.predict(X_test_scaled)),4)
    )

Alpha=0.01 R2= 0.843
Alpha=0.1 R2= 0.843
Alpha=1 R2= 0.8424
Alpha=10 R2= 0.8376
Alpha=100 R2= 0.8237

In [34]:
""" 
Small alpha
≈ Linear Regression

Large alpha
→ Strong coefficient shrinkage

Very large alpha
→ Underfitting
"""

' \nSmall alpha\n≈ Linear Regression\n\nLarge alpha\n→ Strong coefficient shrinkage\n\nVery large alpha\n→ Underfitting\n'

In [35]:
#Laaso regresison
from sklearn.linear_model import Lasso 
lasso = Lasso(alpha=1.0)

In [36]:
lasso

Lasso()

In [37]:
lasso.fit(X_train_scaled, y_train)

Lasso()

In [39]:
y_pred_lasso = lasso.predict(X_test_scaled)

In [40]:
lasso_coeff = pd.DataFrame({
    "Feature" : X.columns,
    "Coeff": lasso.coef_
})
lasso_coeff

        Feature     Coeff
0     cylinders -0.000000
1  displacement -0.000000
2    horsepower -0.018393
3        weight -4.535544
4  acceleration  0.000000
5    model_year  2.099907
6  origin_japan  0.000000
7    origin_usa -0.538430

In [ ]:
"""
model can predict MPG reasonably well using:

weight
model_year
origin_usa
horsepower
"""

In [41]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

print("R2 Score :", r2_score(y_test, y_pred_lasso))
print("MAE      :", mean_absolute_error(y_test, y_pred_lasso))
print("MSE      :", mean_squared_error(y_test, y_pred_lasso))
print("RMSE     :", np.sqrt(mean_squared_error(y_test, y_pred_lasso)))

R2 Score : 0.8372767878097774
MAE      : 2.3466976030885958
MSE      : 9.239996122974897
RMSE     : 3.039736192990256

In [47]:
""" 
Linear Regression R2 : 0.8430426014268103
Ridge R2 : 0.842362621546747
Lasso R2: 0.8372767878097774
"""

' \nLinear Regression R2 : 0.8430426014268103\nRidge R2 : 0.842362621546747\nLasso R2: 0.8372767878097774\n'

In [42]:
# Elastic net 
from sklearn.linear_model import ElasticNet
elastic = ElasticNet(
    alpha=1.0,
    l1_ratio=0.5
)
"""
l1_ratio = 0
    ↓
Pure Ridge

l1_ratio = 1
    ↓
Pure Lasso

l1_ratio = 0.5
    ↓
50% Ridge + 50% Lasso
"""

'\nl1_ratio = 0\n    ↓\nPure Ridge\n\nl1_ratio = 1\n    ↓\nPure Lasso\n\nl1_ratio = 0.5\n    ↓\n50% Ridge + 50% Lasso\n'

In [43]:
elastic.fit(X_train_scaled, y_train)

ElasticNet()

In [44]:
elastic_coeff = pd.DataFrame({
    "Feature": X.columns,
    "Coeff": elastic.coef_
})

elastic_coeff

        Feature     Coeff
0     cylinders -0.822528
1  displacement -0.967454
2    horsepower -0.955690
3        weight -1.702548
4  acceleration  0.000000
5    model_year  1.539806
6  origin_japan  0.304327
7    origin_usa -0.701226

In [45]:
y_pred_elastic = elastic.predict(X_test_scaled)

In [46]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

print("R2 Score :", r2_score(y_test, y_pred_elastic))
print("MAE      :", mean_absolute_error(y_test, y_pred_elastic))
print("MSE      :", mean_squared_error(y_test, y_pred_elastic))
print("RMSE     :", np.sqrt(mean_squared_error(y_test, y_pred_elastic)))

R2 Score : 0.8093823034042484
MAE      : 2.470073064727381
MSE      : 10.823943024528004
RMSE     : 3.289976143458795

In [48]:
""" 
Linear Regression R2 : 0.8430426014268103
Ridge R2 : 0.842362621546747
Lasso R2: 0.8372767878097774
ElasticNet R2 : 0.8093823034042484
"""

' \nLinear Regression R2 : 0.8430426014268103\nRidge R2 : 0.842362621546747\nLasso R2: 0.8372767878097774\nElasticNet R2 : 0.8093823034042484\n'

In [49]:
"""
First Observation

For this dataset:

Linear Regression ≈ Ridge > Lasso > Elastic Net

This tells us something important.

There is no major overfitting problem

If Ridge were significantly better than Linear Regression:

Linear = 0.78
Ridge  = 0.84

then regularization would be helping a lot.

But here:

0.8430
vs
0.8424

Difference is tiny.

So Linear Regression is already doing quite well.
"""

'\nFirst Observation\n\nFor this dataset:\n\nLinear Regression ≈ Ridge > Lasso > Elastic Net\n\nThis tells us something important.\n\nThere is no major overfitting problem\n\nIf Ridge were significantly better than Linear Regression:\n\nLinear = 0.78\nRidge  = 0.84\n\nthen regularization would be helping a lot.\n\nBut here:\n\n0.8430\nvs\n0.8424\n\nDifference is tiny.\n\nSo Linear Regression is already doing quite well.\n'

In [51]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [58]:
lasso = Lasso()
param_grid = {
    "alpha" : [0.001, 0.01, 0.1, 1, 10, 100]
}
grid_search = GridSearchCV(
    estimator= lasso,
    param_grid= param_grid,
    scoring= "r2",
    verbose=2,
    cv=5
)
grid_search

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [59]:
grid_search.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [60]:
grid_search.best_params_

{'alpha': 0.1}

In [61]:
grid_search.best_score_

np.float64(0.8038445561127245)

In [62]:
grid_search.cv_results_

{'mean_fit_time': array([0.00149422, 0.00141969, 0.00102186, 0.00040402, 0.00112824,
        0.00050039]),
 'std_fit_time': array([0.00080795, 0.00052428, 0.00056055, 0.00049489, 0.00011799,
        0.00062773]),
 'mean_score_time': array([0.00155778, 0.00065885, 0.00121088, 0.00039868, 0.00062723,
        0.00030675]),
 'std_score_time': array([0.00093811, 0.00054093, 0.00150265, 0.00048829, 0.00051215,
        0.00041287]),
 'param_alpha': masked_array(data=[0.001, 0.01, 0.1, 1.0, 10.0, 100.0],
              mask=[False, False, False, False, False, False],
        fill_value=1e+20),
 'params': [{'alpha': 0.001},
  {'alpha': 0.01},
  {'alpha': 0.1},
  {'alpha': 1},
  {'alpha': 10},
  {'alpha': 100}],
 'split0_test_score': array([ 0.81141296,  0.81149033,  0.81116456,  0.80328814, -0.01306229,
        -0.01306229]),
 'split1_test_score': array([ 0.80616973,  0.80650601,  0.80343211,  0.76203838, -0.00112353,
        -0.00112353]),
 'split2_test_score': array([ 0.80928987,  0.80916556,  0.80649655,  0.76905122, -0.00397251,
        -0.00397251]),
 'split3_test_score': array([ 0.82164047,  0.82176175,  0.82063676,  0.80586082, -0.05239458,
        -0.05239458]),
 'split4_test_score': array([ 0.76685884,  0.76898477,  0.7774928 ,  0.75203237, -0.0050067 ,
        -0.0050067 ]),
 'mean_test_score': array([ 0.80307437,  0.80358168,  0.80384456,  0.77845418, -0.01511192,
        -0.01511192]),
 'std_test_score': array([0.01883619, 0.01805403, 0.01440263, 0.02201752, 0.0190582 ,
        0.0190582 ]),
 'rank_test_score': array([3, 2, 1, 4, 5, 5], dtype=int32)}

In [ ]:
# best_estimator_ : estimator that was chosen by the search, i.e. estimator which gave highest score (or 
#  small loss if specified) on the left out data. Not available if refit = False

In [64]:
# grid_search.best_estimator_
best_lasso = grid_search.best_estimator_
y_pred = best_lasso.predict(X_test_scaled)

In [65]:
lasso_r2 = r2_score(y_test, y_pred)
lasso_r2

0.8372176798414681

In [ ]:
# randomized search : only param_grid change to param_distributon

In [67]:
from sklearn.model_selection import RandomizedSearchCV

lasso = Lasso()

param_distributions = {
    'alpha': [0.001, 0.01, 0.1, 1, 10, 100]
}

random_search = RandomizedSearchCV(
    estimator=lasso,
    param_distributions=param_distributions,
    n_iter=5,
    scoring='r2',
    cv=5,
    verbose=2,
    random_state=42
)
random_search

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=5,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   random_state=42, scoring='r2', verbose=2)

In [68]:
""" 
n_iter : select random n values from param_distributions 
random_state : reproduce the result 
"""

' \nn_iter : select random n values from param_distributions \nrandom_state : reproduce the result \n'

In [70]:
random_search.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=5,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   random_state=42, scoring='r2', verbose=2)

In [71]:
random_search.best_params_

{'alpha': 0.1}

In [72]:
random_search.best_score_

np.float64(0.8038445561127245)

In [73]:
best_lasso_randomized = random_search.best_estimator_

In [74]:
y_pred_randomizedSearchCV = random_search.best_estimator_.predict(X_test_scaled)
y_pred_randomizedSearchCV

array([31.90092284, 29.38535593, 20.7301983 , 16.88779961, 12.86808584,
       26.89889278, 27.95098321,  9.71436778, 17.16078864, 21.7008025 ,
       12.57687974, 35.50201296, 24.75665152, 14.06957242, 23.6931523 ,
        7.07191622, 29.64355736, 25.41293005, 15.91840718, 35.46872848,
       24.60237132, 18.84123437, 28.0293946 , 28.64859956, 14.83724592,
       34.62755522, 26.71836949, 24.81891059, 21.60788467,  8.95951891,
       28.40826353, 35.38349867, 19.5531132 , 25.84739028, 33.65576918,
       12.26019089, 23.17129226, 21.40539657, 12.92064603, 27.7875663 ,
       26.46839012, 27.77882082, 22.01895731,  8.08150113, 24.53302114,
       34.28789198, 27.67034393, 25.82434056, 23.74569035, 28.59389647,
       22.15441524, 33.13437571, 32.07194826, 10.84932133, 27.89510592,
        9.9056546 , 19.20752874, 29.57823191, 22.8946764 , 20.24046852,
       16.00789783, 31.12767979, 23.87385981, 21.87229031, 20.75456987,
       25.36033994, 24.94790606, 31.99726117, 27.47323338, 12.98376273,
       31.03353641, 13.5268518 ,  9.72914573, 18.80612207, 27.40910108,
       21.91211022, 20.2516698 , 29.4578461 , 30.23558392, 19.87321838,
       15.15033532, 25.18069107, 35.15391651, 33.38613317, 25.78599615,
       11.13108211, 32.36454188, 30.07977008, 26.64756595,  8.55160006,
       15.2707504 , 31.19722131, 27.40080004, 32.4791242 , 25.1477619 ,
       32.32192632, 29.93441527, 23.34888969, 26.71589988, 13.01065943])

In [75]:
r2_score(y_test, y_pred_randomizedSearchCV)

0.8372176798414681

In [76]:
#_______________________________________________________________________________________________

In [77]:
elastic_net = ElasticNet()

In [78]:
param_grid = {
    'alpha': [0.001, 0.01, 0.1, 1, 10, 100],
    'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]
}

In [79]:
grid_search = GridSearchCV(
    estimator=elastic_net,
    param_grid=param_grid,
    scoring='r2',
    cv=5,
    verbose=2
)

In [80]:
grid_search.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.7; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.7; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.7; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.7; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.7; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100],
                         'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]},
             scoring='r2', verbose=2)

In [81]:
grid_search.best_params_

{'alpha': 0.01, 'l1_ratio': 0.5}

In [82]:
grid_search.best_score_

np.float64(0.8037394793032642)

In [83]:
best_elastic = grid_search.best_estimator_

In [84]:
y_pred = best_elastic.predict(X_test_scaled)

In [85]:
r2 = r2_score(y_test, y_pred)
print("ElasticNet Test R2 :", r2)

ElasticNet Test R2 : 0.8410993660870532